packages/convergence/tests/converge-on-test.js
Because the timeout is created just before the convergence has started, sometimes the convergence finishes milliseconds before you might think it would
=> Adjust test timing

.circleci/config.yml
~The `npm publish` command needs `node_modules` from the cache~
The new `each-pkg` script needs `node_modules` from the cache
=> Fix Circle deploy job

.circleci/config.yml
[By default, scoped packages are private. To publish a public scoped package, we need to set the access option when publishing it.](https://docs.npmjs.com/getting-started/scoped-packages#publishing-a-scoped-package)
=> Publish public packages

packages/convergence/README.md, packages/convergence/package.json
On npm, relative file paths do not display correctly. We can point the image URLs to their raw paths on GitHub so that npm can properly display them in the README.
In order for npm to show the new README, we need to publish a new version of the package.
=> Update README image URLs

packages/convergence/.babelrc, packages/convergence/package.json, packages/convergence/rollup.config.js, packages/convergence/tests/mocha.opts, yarn.lock
When working with multiple packages, yarn workspaces hoists shared dependencies into the workspace root. _It does not symlink modules._ Babel 6 is incompatible with this directory structure unless we symlink all dependent modules ourselves. Babel 7, however, is compatible with the workspace's `node_module` structure.
`babel-plugin-remove-comments` has been deprecated. Instead, we can use `comments: false` in our babel config.
`@babel/plugin-external-helpers` was previously required so `rollup-plugin-babel` could deduplicate babel helpers. `rollup-plugin-babel@4.0.0-beta.0` (uses Babel 7) no longer needs this plugin, so it was removed.
=> Upgrade to babel 7

.circleci/config.yml
When packages depend on one another, they are symlinked in the workspace root. Importing one of these symlinked packages requires that the package be built first.
We previously ran `test` & `build` steps in parallel, but the `build` step should happen first so that tests can find the built packages.
You can reproduce this on the `bigtest-mocha` branch by running the tests before building.
After cherry-picking this commit, that branch passes successfully in Circle. 
We should probably automatically build packages before running tests locally. To avoid extra work, we should only build packages that haven't already been built. We can create a script that utilizes `each-pkg` to only build packages that don't already have a fresh build. But for now, simply building the dependent packages …
=> Build before testing in CircleCI

bin/each-pkg
During early iterations of `each-pkg` the current directory was set as the package path for the `npm view .\ version` command. When not inside of that package's directory, the command does not return the expected version number. Instead, we can use the package's `name` to check the latest version.
=> Use package name instead of path for version check

packages/mocha/.babelrc, packages/mocha/README.md, packages/mocha/package.json, packages/mocha/rollup.config.js, packages/mocha/src/index.js, packages/mocha/tests/fixtures/it-fixture.js, packages/mocha/tests/fixtures/it.always-fixture.js, packages/mocha/tests/fixtures/it.always.only-fixture.js, packages/mocha/tests/fixtures/it.only-fixture.js, packages/mocha/tests/helpers.js, packages/mocha/tests/it-test.js, packages/mocha/tests/it.always-test.js, packages/mocha/tests/it.pause-test.js, packages/mocha/tests/mocha.opts, yarn.lock
`@bigtest/mocha` simply wraps assertions passed to mocha's `it` with a `Convergence` from `@bigtest/convergence`. It uses the timeout specified using mocha's `timeout` method.
``` javascript
it('passes within 1 second', function() {
expect(total).to.equal(5);
}).timeout(1000);
```
=> @bigtest/mocha

packages/mocha/package.json
The @bigtest/mocha JavaScript sources are written using ES modules, but not every system that will be consuming @bigtest/mocha understands them. For those systems (specifically Node runtimes), we build an AMD equivalent using rollup.js and put the index for it in `dist/index.js`. On the other hand, if your system understands modules (like a webpack or a broccoli build) then you want to skip the intermediary build and just use the native sources directly.
We can tell systems where the ES module representing the entry point is, by using the "module" property and pointing it to the primary module for our library.
=> Add "module" index for systems that can consume ES modules.

packages/convergence/package.json
see https://github.com/thefrontside/bigtest/pull/18
=> Make convergence available as an es module with "module" entry point

packages/convergence/CHANGELOG.md, packages/convergence/rollup.config.js, packages/mocha/rollup.config.js
To remove comments from compiled files, `comments: false` needs to be at the root of babel's config.
=> Fix comment removal

.circleci/config.yml, bin/each-pkg, bin/tag-pkg, package.json, packages/convergence/package.json, packages/mocha/package.json, yarn.lock
#21 - ~Instead of tagging via each package's`postpublish` hook, tagging is done by the CI. Since the tags also need to be pushed by the CI, tagging can be it's responsibility. This also prevents us from needing to add `postpublish` hooks to every future package we add.~ See below
=> Automatically tag new package versions

packages/mocha/CHANGELOG.md, packages/mocha/README.md, packages/mocha/src/index.js, packages/mocha/tests/fixtures/hooks-fixture.js, packages/mocha/tests/fixtures/hooks-timing-fixture.js, packages/mocha/tests/fixtures/it-fixture.js, packages/mocha/tests/fixtures/it.always-fixture.js, packages/mocha/tests/fixtures/it.always.only-fixture.js, packages/mocha/tests/fixtures/it.only-fixture.js, packages/mocha/tests/hooks-test.js
As per some [discussion in #23](https://github.com/thefrontside/bigtest/pull/23#discussion_r160558026), this wraps Mocha's hooks to automatically run returned convergences within the current timeout period.
=> Convergent mocha hooks

.circleci/config.yml, yarn.lock
These dependencies were out of date and more importantly, failing to kick the yarn cache on our CI, to let it know that a re-install is necessary.
This updates the global yarn.lock to point to the most recent versions of pretender and fake-xml-http-request, which is technically more correct, but also has desired side-effect of killing the cache
=> Update root yarn.lock

packages/mocha/package.json, packages/mocha/src/index.js, packages/mocha/src/mocha.js
The mocha entrypoint has not yet been optimized to work with browser bundles without first disabling certain node modules.
https://github.com/mochajs/mocha/issues/2448
In a browser environment, mocha is usually included before the tests and has defined it's functions within the global context. Requiring mocha directly is now disabled in browser environments via the `browser` field in this package's `package.json` file.
Added a `mocha.js` file which imports all of mocha's exports, and defaults the relevant ones with the defined globals. Since mocha is now disabled for browsers, this will effectively export the globally defined mocha functions as named exports.
=> Disable requiring mocha directly in browser environments

packages/convergence/CHANGELOG.md, packages/convergence/README.md, packages/convergence/src/convergence.js, packages/convergence/tests/convergence-test.js
Convergences are basically Monoids, and by extension SemiGroups. They should support an `.append()` method to "smash" two convergences together.
Should we also have a `.reduce()` method? Or I also considered allowing `.append()` to take multiple arguments like `.append(...convergences)`. Which would be similar to a monoid's `reduce`
=> Add convergence .append() method

packages/convergence/CHANGELOG.md, packages/convergence/package.json, packages/convergence/src/convergence.js, packages/convergence/tests/convergence-test.js
This allows us to create custom convergence by extending the `Convergence` class.
Where we were previously calling `new Convergence` in our methods, we need to call `new this.constructor` to allow subclasses to be created when extending the convergence class.
The constructor arguments have been generalized so that subclasses can handle their own initialization with different options as long as they call `super(options, prev)`. Creating a convergence using `new Convergence(timeout)` is still supported as the public API for creating convergences.
I also bumped the version so we can release this with the same PR.
=> Make Convergences Extendable

README.md
Bigtest is still very much a loose collection of tools that folks have to manually integrate. Each tool has a very complete README, but the main README is still one of the few places to discover _all_ of the parts.
This adds a link to the interaction package so that folks can find it from the main project.
=> Link @bigtest/interaction from the main README

packages/mocha/src/index.js, packages/mocha/tests/fixtures/it.always-fixture.js, packages/mocha/tests/it.always-test.js
When using `it.always` the mocha default timeout of 2000ms is used. This makes testing with `it.always` much slower.
Mocha `Runnable` instances have a chainable method interface. So returning `test.timeout(50)` allows us to have a default timeout of `50ms` and still allow changing the timeout with `it.always(...).timeout(100)`.
- Is 50ms a good default timeout for `it.always`? Or should we go a little higher to say 100ms? At 50ms, the test will run at least 2-3 times (because it aborts about ~20ms before the timeout)
=> Default mocha `it.always` timeout to 100ms

packages/convergence/CHANGELOG.md, packages/convergence/README.md, packages/convergence/package.json, packages/convergence/src/converge-on.js, packages/convergence/src/convergence.js, packages/convergence/tests/converge-on-test.js, packages/convergence/tests/convergence-test.js, packages/interaction/karma.conf.js, packages/mocha/CHANGELOG.md, packages/mocha/package.json, yarn.lock
After using `@bigtest/mocha` in  real projects, it seems as though `it.always` [can sometimes be flakey](https://travis-ci.org/folio-org/ui-eholdings/builds/346465220).
After digging into this issue a little bit, I found that the problem is with how we attempt to resolve or reject the converging promise _before the timeout_.
When we created `@bigtest/convergence`, the goal was to help mitigate waiting for the right time to run our tests. What we ended up doing in our convergence is trying to _wait for the right time to settle the promise_. So unknowingly, we ended up creating a very similar problem.
As seen in [these tests](https://circleci.com/gh/thefrontside/bigtest/492), when a convergent assertion has some latency associated with it's execution, it is resolved or rejected _after the …
=> Redefine convergence timing

packages/mocha/CHANGELOG.md, packages/mocha/package.json
Looks like I accidentally forgot to increment the version number in [this commit](https://github.com/thefrontside/bigtest/pull/54/commits/a5a2f0705c96a6c6f633d3b947470378f253239e)
=> Actually release @bigtest/mocha v0.2.2

packages/interaction/CHANGELOG.md, packages/interaction/package.json, packages/interaction/src/properties/is-present.js, packages/interaction/tests/properties/is-present-test.js, yarn.lock
Fixes #58.
When the `selector` is not provided, the property should work with the page's root element. For `isPresent`, it throws an error when the root does not exist when it should return `false`.
Wrap the return statement in a try-catch block that returns `false` when an error is thrown.
Also upgraded the `@bigtest/convergence` dependency to bring in the new convergence timing.
=> Fix @bigtest/interaction isPresent page property

packages/convergence/CHANGELOG.md, packages/convergence/src/convergence.js, packages/convergence/tests/convergence-test.js
This was previously, loosely, supported due to the currying nature of `.do()` blocks within a promise. This makes stats for these blocks actually report the true times and return values of the promises.
When the result of a `.do()` block is thenable, the stats are calculated when it resolves. Otherwise, they are calculated right away.
If a promise takes longer than the remaining timeout, an error will be thrown after the promise resolves. This same error will now also be thrown before assertions if the elapsed time exceeds the allotted timeout. Before, if a `.do()` block made the convergence exceed the timeout, the following convergent assertion could be called with a negative timeout. That is no longer possible when throwing the new timeout error.
=> Add full support for returning promises in convergence `.do()` blocks

packages/convergence/CHANGELOG.md, packages/convergence/README.md, packages/convergence/package.json, packages/convergence/src/convergence.js, packages/convergence/src/index.js, packages/convergence/src/utils.js, packages/convergence/tests/convergence-test.js, yarn.lock
When a convergence is returned from a `.do()` block, we should run the returned convergence under the current timeout.
When the result of a `.do()` block has a convergence interface, it is run with the current remaining timeout. To prevent `.always()` in the returned convergence from using the remaining timeout, a `.do()` is added which just continues currying the last returned value from the convergence.
Refactored the `.run()` method since it was getting pretty large. There are two main util functions for it, but they use other util functions in the `utils.js` file.
Also added an `isConvergence` method and exported it. Not only do we need in in this package, but `@bigtest/mocha` could also use it. Not only is it exported, but it's available as `Convergence.isConvergence` to mimic …
=> Handle returned convergences in `.do()` blocks

packages/interaction/CHANGELOG.md, packages/interaction/package.json, packages/interaction/src/interaction.js, packages/interaction/tests/interaction-test.js
A pause method that stops the convergence from continuing would be helpful when debugging applications in the middle of an interaction.
Updated `@bigtest/convergence` to `0.5.0`
The `.pause()` method on `Interaction` simply returns an unresolving promise from a `.do()` block which will effectively stop the convergence from continuing.
=> Add interaction pause method

packages/mocha/CHANGELOG.md, packages/mocha/package.json, packages/mocha/src/utils.js, yarn.lock
Makes use of the new `isConvergence` helper.
Also releases `@bigtest/mocha` `v0.3.2`
=> Update mocha convergence

.circleci/config.yml, packages/mocha/CHANGELOG.md, packages/mocha/package.json, packages/mocha/src/utils.js, packages/mocha/tests/fixtures/hooks-timing-fixture.js, packages/mocha/tests/hooks-test.js
When an each hook is run more than once, it retains the old timeout. When our helper sets the timeout to `0`, this causes the next run to give the convergence a timeout of `0`.
By setting the timeout back to the original timeout before the convergence finishes, we can ensure that the next run of the hook still has the correct timeout.
=> Fix mocha each hook timeout error

packages/convergence/CHANGELOG.md, packages/convergence/package.json, packages/convergence/src/convergence.js, packages/convergence/tests/convergence-test.js, packages/interaction/CHANGELOG.md, packages/interaction/package.json, yarn.lock
This will add support for the `async`/`await` syntax with convergences without needing to call `.run()`.
A `.then()` method is all that is necessary to support this syntax. By always resolving with the value of the last function in the stack, we can allow convergences to resolve to this value when using `async`/`await`.
``` javascript
async function clickElement(selector) {
// will resolve to the element when it exists
let $node = await new Convergence().once(() => {
let el = document.querySelector('.element');
return !!el && el;
});
$node.click();
}
```
I went ahead and upgraded `@bigtest/interaction` to make use of this as well. So this PR will release two of our packages.
=> Make Convergences & Interactions thennable

packages/convergence/CHANGELOG.md, packages/convergence/README.md, packages/convergence/src/convergence.js, packages/convergence/tests/convergence-test.js
Addresses #72 
`.when()` reads better in most situations. 
Search-and-replaced pretty much every instance of `once` that made sense.
To avoid breaking changes, `.once()` was aliased to `.when()`.
=> Change convergence `.once()` to `.when()`

packages/convergence/CHANGELOG.md, packages/convergence/src/converge-on.js, packages/convergence/src/convergence.js, packages/convergence/src/utils.js, packages/convergence/tests/converge-on-test.js, packages/convergence/tests/convergence-test.js
While working on `@bigtest/interaction`, I realized that this is currently not possible with convergences:
``` javascript
new Convergence().do(function() {
console.log(this.timeout())
})
```
It might not seem useful in the context of convergences, so here's an example using `@bigtest/interaction`:
``` javascript
// scrolls to the bottom of the page when there is room to scroll
await new Interactor('#page')
.when(function() {
return this.$root.scrollHeight > this.$root.offsetHeight
})
.do(function() {
return this.scroll({ top: this.$root.scrollHeight })
})
```
First, bind the instance context to any `assertion`s and `callback`s created using `#when()`, `#always()`, `#do()`, etc.
Previously, `convergeOn` curried its own context onto the assertion ~and always overrode any context bound to …
=> Convergence Instance Context

packages/convergence/CHANGELOG.md, packages/convergence/package.json, packages/interaction/CHANGELOG.md, packages/interaction/package.json
This releases `@bigtest/convergence` 0.7.0 and `@bigtest/interaction` 0.4.0 at the same time due to test failures when trying to release `@bigtest/convergence` 0.7.0 alone (#91).
This highlights some potential pitfalls of a monorepo. Since the dependency in `@bigtest/interaction` was automatically linked, recent changes utilized an unreleased feature of `@bigtes/convergence`. When changing the version number of `@bigtest/convergence`, the link was broken and `@bigtest/interaction` used the version from npm instead, which did not support `#when()`. Failures can be seen for that release [here](https://circleci.com/gh/thefrontside/bigtest/773).
Released packages are not effected since the version numbers are correct, but this requires us to release these two packages at once to avoid CI/CD …
=> @bigtest/convergence v0.7.0 & @bigtest/interaction v0.4.0

packages/website/.editorconfig, packages/website/.stylelintrc, packages/website/package.json, packages/website/src/components/Footer.tsx, packages/website/src/components/Header.tsx, packages/website/src/components/IconLink.ts, packages/website/src/components/ReachOut.tsx, packages/website/src/components/SubscribeForm.tsx, packages/website/src/pages/index.tsx, packages/website/src/theme/base.ts, yarn.lock
We want to have a consistent code for the website. Tooling can contribute to achieve that goal.
Min had introduced `prettier` before. This PR applies the checks by prettier and adds `stylelint` configured to work with `styled-components`. 
New commands are introduced. 
- `lint:ts`: runs prettier to check the format of the typescript files. 
- `lint:styles`: runs `stylelint` to check the format of `styled-components` inside typescript files.
- `lint`: runs both lint checks. I decided to us `;` instead of `&&` to provide the full picture to a developer when they run `lint`. If we used `&&`, the developer could think "oh great, I just have this ts errors" and then when they run it again to check what they fixed, new style errors pop up.
`format:ts`: was renamed because styles format cannot …
=> Website: Applies prettier and introduces stylelint

.gitignore, packages/agent/.eslintrc.json, packages/agent/.gitignore, packages/agent/README.md, packages/agent/app/agent.ts, packages/agent/app/harness.ts, packages/agent/app/index.html, packages/agent/bin/helpers.ts, packages/agent/bin/run-parcel.ts, packages/agent/bin/start.ts, packages/agent/index.ts, packages/agent/package.json, packages/agent/test/agent.test.ts, packages/agent/tsconfig.json, yarn.lock
Motivation
----------
There are a couple of problems with our current setup of having the agent living inside the bigtest/server.  First and foremost, we're building the agent application code every single time and that causes a lot of unwanted startup time. We're willing to deal with this in development, but this is really going to add significant time to work with bigtest applications in real life, and also consume lots of unecessary computational resources in CI.
Approach
--------
This extracts the agent server app into a pre-built web application that uses parcel and microbundle to compile the HTML and typescript respectively.
In addition, an enhancement has been made to have the agent server bind to optionally bind to a different port every time.
The actual agent application lives in …
=> Add @bigtest/agent

packages/website/gatsby-config.js, packages/website/package.json, packages/website/src/components/Layout.tsx, yarn.lock
#122 
I rechecked the package that I using the first time, `gatsby-plugin-web-font-loader`, and realized that the plugin defaults to async font loading. Under the hood, it uses [typekit/webfontloader](https://github.com/typekit/webfontloader) which does not default to async (but offer the option for it).
My solution was to keep it simple and opt for Typescript's default solution: a stylesheet link. They've done a lot of research and work to make it work as good as possible. 
There is a brief flash the first time you visit the page (when you don't have the fonts cached), but in subsequent pages and reloads the fonts work pretty smoothly. 
If we wanted to completely remove any sight of unstyled text, then we could implement  [typekit/webfontloader](https://github.com/typekit/webfontloader) …
=> Use Typekit's link directly

packages/agent/bin/start.ts, packages/agent/index.ts, packages/agent/package.json, packages/agent/test/agent.test.ts
We've decided, that any port allocation should be done ahead of time, that way we know what the static configuration of the server is going to be and we don't need to block startup based on different services acquiring urls.
=> Better connectback api

.github/workflows/preview.yml, .github/workflows/release.yml
With all the new changes to bigtest, we need the mechanism to automatically publish releases upon merging pull requests to the master branch.
I've gone ahead and updated the `synchronize-with-npm` action on `@thefrontside/actions` to support monorepos. You can read more about it [here](https://github.com/thefrontside/actions/pull/54). 
And I ran that action from that branch on bigtest [here](https://github.com/thefrontside/bigtest/runs/454029814?check_suite_focus=true) with no issues... except I'm getting a `Creating a browser bundle that depends on Node.js built-in module ('path'). You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins` notification for `packages/agent` but that doesn't seem to prevent it from building and publishing properly.
Oh and I also …
=> Add release workflow and rename preview workflow

.github/workflows/actions.yml, README.md, netlify.toml, package.json, packages/agent/package.json, packages/cli/package.json, packages/convergence/package.json, packages/interactor/package.json, packages/project/package.json, packages/website/package.json
Motivation
----------
Yarn workspaces gives preference to local packages inside the monorepo over anything listed in the package.json. So, for example, the contents of the `packages/agent` directory is preferred over the `@bigest/agent` npm packages.
Approach
----------
As we add many independent NPM packages to the monorepo, this makes development awkward since you need to build your package ahead of time. This adds a `yarn prepack` script to the root package that fans out a prepack over all of the packages. That way, you can run it once before hacking on your individual package, and all the other packages are ready to be used.
Why `prepack` and not `build`?
------------------------------
`prepack` is the npm package state that is "just before the tarball is created". In other words, the …
=> Prepack for CI and for development

packages/website/src/components/DidYouKnow.tsx, packages/website/src/components/GreetLegacyUsers.tsx, packages/website/src/components/Hero.tsx, packages/website/src/components/Text.ts, packages/website/src/components/WarningBox.tsx, packages/website/src/components/WhyBigTest.tsx, packages/website/src/pages/docs.tsx, packages/website/src/pages/guides.tsx, packages/website/src/pages/index.tsx, packages/website/static/_redirects
We changed the website, but still have routes from the old site that are missing in the new site.
This PR introduces a placeholder page for Guides and one for Docs. It also adds redirects for any subroute of /guides and /docs to their respective placeholder page with a note about the changes.
=> Placeholder /guides and /docs pages with redirects for children routes

packages/server/bin/start.ts, packages/server/package.json, packages/server/src/connection-server.ts, packages/server/src/index.ts, packages/server/src/manifest-builder.ts, packages/server/src/manifest-generator.ts, packages/server/src/manifest-server.ts, packages/server/src/orchestrator.ts, packages/server/src/orchestrator/atom.ts, packages/server/src/test.ts, packages/server/test/helpers.ts, packages/server/test/manifest-builder.test.ts, packages/server/test/manifest-generator.test.ts, packages/server/test/orchestrator.test.ts, yarn.lock
> Migrated from https://github.com/bigtestjs/server/pull/103
The fingerprinted filename is stored in the state.
One minor change in this PR is that the orchestrator no longer creates the atom, but must be supplied with one. The reason for this is that we need to be able to extract data from the atom in our tests, and there is no other way of getting hold of it.
=> Fingerprint manifest so they get unique URLs

packages/website/src/pages/docs.tsx, packages/website/src/pages/guides.tsx
=> Fix renovation note typos

packages/website/gatsby-config.js
Motivation
----------
People are actually using our site and sharing links to it.
Approach
--------
Use some, any description. It doesn't have to be great, but it needs to not be obviousl placeholder text
=> Don't use placeholder text in site meta description

packages/agent/package.json
Prior to 0.5.1, effection will not work with `regeneratorRuntime` since it used native generator function prototype to test if an object was a generator. Since the agent needs to support any old browser, it uses `regeneratorRuntime` instead of native generators.
This upgrades the agent to the first version of effection that uses `regeneratorRuntime`
=> Upgrade agent to use effection 0.5.1

.github/workflows/lint.yml, package.json, packages/agent/package.json, packages/cli/package.json, packages/convergence/package.json, packages/interactor/package.json, packages/project/package.json, packages/server/bin/parcel-server.ts, packages/server/package.json, packages/server/test/command-server.test.ts, packages/server/test/helpers.ts, packages/server/test/helpers/world.ts, packages/server/test/manifest-builder.test.ts
Now that we have everything in a monorepo, it's time to get our listing story in line.
This adds a lint workflow to run on each PR that delegates to each package (and also fixes the current crop of listing errors)
=> Lint all the things

.github/workflows/test.yml
We're running the tests in the `actions.yml` workflow, and the name in the box reads "Node 12"
Instead, this should be called `tests.yml` and "tests"
=> Call the testing workflow what it is

packages/suite/.eslintrc.json, packages/suite/.gitignore, packages/suite/README.md, packages/suite/index.ts, packages/suite/package.json, packages/suite/tsconfig.json
Motivation
----------
There are several interfaces that we use across different components to work with tests. Most of them don't need to know about the specifics of the implementation of the test, but instead just the structure of them. There are some systems like the harness and any DSL that will need to know about the test implementation interface however.
Approach
----------
This adds a `@bigtest/suite` package that will serve as a home for the shared interfaces, some of which will need to be bundled on both the browser as well as in `node`. There are two separate interfaces for `Test` and `TestImplemenation` that represent the structure as well as the "live functions" respectively.
In the declaration of the interfaces themselves, there is some duplication for the sake of readability …
=> Add Test interfaces for use across components

packages/server/src/proxy.ts
Motivation
-----------
Similar to the way that express sending `etag` headers in the response was causing stale copies of the harness-injected application because the browser would send back the `if-none-match`. If we have `last-modified` headers in the response, then the browser would send a request with a `if-modified-since` header that would trigger a 304 from express. Worse, when express responded this way, it only checks the fstat to check the timestamp of the file on the filesystem and did not even bother to do any further introspection before sending back a 304 response. As a result, there were no `Content-Type` or `Content-Encoding` headers being set. This meant that our special code-path for HTML files was not being hit at all.
The reason we didn't see this before was that we had …
=> Disable timestamp caching for proxied html responses

packages/server/src/connection-server.ts, packages/server/src/manifest-builder.ts, packages/server/src/orchestrator/atom.ts, packages/server/test/command-server.test.ts
Handy as they are, using TypeScript with Ramda lenses can be annoying at best, and perilous at worst. There are two basic problems:
1. lens operations are cumbersome in that you have to store a reference to not only the child and the root value, but also the lens.
2. the lenses erase type information. Ideally they shouldn't since they don't in other statically typed languages, but they don't type easily since TS does not support higher kinded types.
This solves both of those problem by capturing a lens into a `Slice` object. That way, there's no need to construct an extra referenc, and all of the operations on that slice are implicity happening on the focus of that lens. It solves the typing problem by the fact that `Slice`s are parameterized with the type of the lens's focus. While it …
=> Use atomic slices to improve type-checking of lens operations

packages/server/src/effection/node.ts
It's sometimes useful to get a dump of all effection processes to see what's going on. This adds a signal handler so we can send the SIGUSR1 signal to a process to trigger a console dump of the current state.
=> Can send USR1 to process to print effection backtrace

packages/server/src/manifest-generator.ts, packages/server/src/orchestrator/atom.ts, packages/server/src/test.ts
It makes generating paths to tests trickier, since we end up having an odd-looking "undefined" in there somewhere".
=> Make description mandatory again

packages/project/package.json, packages/project/tsconfig.dist.json, yarn.lock
Depends on #181 
This is API is node-only so `microbundle` is overkill. In fact, we don't need any bundling at all.
=> Simplify @bigtest/project build (remove micro bundle)

packages/effection/.eslintrc.json, packages/effection/.gitignore, packages/effection/README.md, packages/effection/package.json, packages/effection/src/events.ts, packages/effection/src/index.ts, packages/effection/test/helpers.ts, packages/effection/test/once.test.ts, packages/effection/tsconfig.dist.json, packages/effection/tsconfig.json, packages/server/bin/watch.ts, packages/server/package.json, packages/server/src/app-server.ts, packages/server/src/client.ts, packages/server/src/effection/child_process.ts, packages/server/src/effection/events.ts, packages/server/src/http.ts, packages/server/src/orchestrator/atom.ts, packages/server/src/proxy.ts, packages/server/src/ws.ts
Motivation
----------
While effection makes working with async processes a lot eaiser, it is still a primitive, and to be truly useful, most of the time what you really want is to be working with higher level constructs. We've built a lot of these constructs for working in a variety of environments: nodejs, event emitters, etc... Now that we a bunch of packages, we need to have these utitilies on-hand so that they can be used everywhere rather than be copy-pasted around like they are now.
Approach
--------
Ideally, we'd like to publish these package in the `@effection` namespace. However, we don't currently have monorepo support set up for effection, and so rather than go through the hassle of that, this just creates a single package that can be shared within the bigtest project itself. …
=> Allow sharing of effection utilities between bigtest packages.

packages/effection/src/ensure.ts, packages/effection/src/index.ts, packages/effection/src/mailbox.ts, packages/effection/src/suspend.ts, packages/effection/test/ensure.test.ts, packages/effection/test/suspend.test.ts, packages/server/src/effection/child_process.ts, packages/server/src/effection/express.ts
These operations can be used to simplify a lot of the code which currently uses control functions, rather than generators.
=> Add suspend and ensure operations 

packages/logging/.eslintrc.json, packages/logging/.gitignore, packages/logging/README.md, packages/logging/package.json, packages/logging/src/index.ts, packages/logging/tsconfig.dist.json, packages/logging/tsconfig.json, packages/server/bin/start.ts, packages/server/package.json, packages/server/test/setup.js
We will want to use the `setLogLevel` function from both the agent and the server. Additionally we might have other logging related utilities in the future.
=> Extract logging into separate package

packages/website/src/components/Header.tsx, packages/website/src/components/WhyBigTest.tsx
Users of v1 did not have a way to access the archived guides if they visited `https://bigtestjs.io`. 
Added a link on the header pointing to `v1` documentation.
=> Add link to v1 docs to header

packages/convergence/package.json
Motivation
----------
The @bigtest/convergence tests are flaky and often fail, and block the code that will ultimately replace it. For example [this failed test run][1] blocked a completely unrelated PR.
Approach
--------
Since we are going to completely re-write convergence, and the current test suite is not maintained, running them on every build is dead weight, especially when they actually block active changes.
[1]: https://github.com/thefrontside/bigtest/pull/194/checks?check_run_id=488143393#step:6:215
=> Disable convergence tests

packages/server/src/command-processor.ts, packages/server/src/orchestrator.ts, packages/server/src/orchestrator/atom.ts, packages/server/src/orchestrator/state.ts, packages/server/test/command-processor.test.ts
The command processor is basically a run-loop for the orchestrator. It picks off commands from its inbox and runs them.
Extracted from #165
=> Add command processor to orchestrator

packages/parcel/src/parcel-process.ts, packages/parcel/test/parcel-process.test.ts
For some reason, parcel does some stuff to make startup more reliable in NODE_ENV=test, so we set this environment variable so our tests are not flaky.
=> Run parcel under test node env

packages/agent/app/agent.ts, packages/agent/app/create-harness.ts, packages/agent/package.json, packages/agent/tsconfig.app.json
For some reason, parcel chooses to compile typescript, but never to actually typecheck the files it builds. To work around this, we run `tsc` manually during prepack so we actually run typechecks.
See:
https://github.com/parcel-bundler/parcel/issues/465
=> Actually typecheck agent code

packages/server/package.json, packages/server/tsconfig.dist.json
Motivation
---------- 
Even using the prepack script, the server package does not include the compiled assets because they are not included in the files property of the package.json That means that the actual code is not shipped to NPM and you end up with `Error: Cannot find module './orchestrator'` when trying to start bigtest server.
As a result, trying to use this in a standalone project was failing: https://github.com/cowboyd/bigtest-example/blob/7367576e770bae3991ac8a859c671fa5281c5bf7/bin/test.js
Approach
----------
This explicitly distributes all of the files in `dist/` along with their typescript declarations with NPM package.
=> Use built assets as package contents

packages/website/src/pages/index.tsx
*Not the other way around* really trips me up because I keep thinking that the other way around is development speeding up tests.
Change it to read: `Tests that speed up development, not slow it down`. It does seem a little redundant.
=> Suggestion for headline improvement

packages/agent/app/parent-frame.ts, packages/agent/app/socket-connection.ts, packages/agent/app/test-frame.ts, packages/agent/src/client.ts, packages/effection/package.json, packages/effection/src/index.ts, packages/effection/src/mailbox.ts, packages/effection/test/mailbox.test.ts, packages/parcel/src/parcel-process.ts, packages/server/src/command-server/websocket.ts, packages/server/src/connection-server.ts, yarn.lock
Make the Mailbox generic over the type of message, this allows us to have more typesafe mailboxes. For now we default this type to `any` so we don't need to specify the type yet, this keeps the diff more manageable.
=> Generic mailbox

package.json
The "killer" feature is that with yarn workspaces, it prints out which workspace it is using before running a command. So instead of getting a bunch of console logs, you'll get:
-> @bigtest/server
runnning command.....
-> @bigtest/parcel
running command......
Helps for debugging order, and just generally knowing wtf is going on.
=> Use latest yarn with volta

.github/workflows/lint.yml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/test.yml
To resolve #119: Currently, BigTest's test workflow is running the test suites one after the other and making the whole process take very long. This pull request is to modify that workflow to run the test suites in parallel. 
And in the spirit of streamlining the testing workflow, this pull request will also resolve #201.
```
name: Test
jobs:
prepack-upload:
cache
yarn install
yarn prepack
tar packages/*/dist
upload tar
download-test:
need: prepack-upload
matrix: [ packages ]
cache
download tar && unzip
yarn install
cd packages/${{ matrix.package }}
yarn test
```
- Split the workflow into two jobs (we need to `yarn install` in both jobs because we need it for both `prepack` and `test`):
- The first job builds and uploads the `dist` directories as an artifact. 
- The second job downloads …
=> Add caching and running tests in parallel to the test workflow

packages/suite/index.ts
The agent and orchestrator need some shared data structures in order to communicate about how the test was run.
=> Add interfaces for collecting results

packages/agent/app/agent.ts, packages/agent/app/create-harness.ts, packages/agent/test/agent.test.ts
Motivation
----------
When we began to implement the result collection for tests in the orchestrator, the most optimal way to do it was to immediately create a tree of "result listeners" for each test, step and result in the entire hiearchy. Because of this, events like 'test:running' are purely informational, and events like 'test:done' are completely unecessary.
Approach
----------
This PR removes `test:done` entirely, and separates out the `run:begin` and `run:end` to fire a `lane:begin` and `lane:end` event from the harness. These are purely informational and not needed except for perhaps some debugging purposes.
=> Optimize agent for orchestrator-controlled result collection

packages/website/package.json, packages/website/src/components/Footer.tsx, packages/website/src/components/GreetLegacyUsers.tsx, packages/website/src/components/ReachOut.tsx
We are moving Frontside's website to `.com` instead of `.io`
Change all the occurrences of `frontside.io` for `frontside.com`.
⚠️This PR should only be merged once records are changed on the domain and emails.
=> Change frontside's domain to .com

packages/server/src/command-server/websocket.ts, packages/server/src/orchestrator/atom.ts
Motivation
----------
When runing tests, we noticed that the publication of query results was actually missing results. Meaning that the atom was getting update correctly, and if we queried it in the GraphQL interface after the complete test run, the state was correct, but the individual subscription results were not all there. The problem was that because `atom.update` is synchronous it was immediately resuming contexts that were yielded to `atom.next()`, but then dispatching the next state before those contexts could start listening to the new state. As a result, states that were being streamed with `atom.next` were getting dropped on the floor. We need a way to publish _every_ subscription result
Approach
--------
For now, we need to keep `atom.set()` synchronous since we don't have …
=> 🐛Never miss an atom state

packages/server/src/client.ts, packages/server/src/command-processor.ts, packages/server/src/command-server.ts, packages/server/src/connection-server.ts, packages/server/src/orchestrator.ts, packages/server/src/orchestrator/atom.ts, packages/server/src/orchestrator/state.ts, packages/server/src/schema.ts, packages/server/src/ws.ts, packages/server/test/.eslintrc.json, packages/server/test/command-processor.test.ts, packages/server/test/command-server.test.ts, packages/server/test/helpers.ts, packages/server/test/helpers/subscription.ts, packages/server/test/helpers/world.ts, packages/server/test/run-tests.test.ts
> depends on #223 #224 
Motivation
----------
While the agent supports running tests and streaming results back to the server, we don't currently have a way to interface with those results via the GraphQL API. In our planned scenario, you will issue a `run` mutation and then subscribe to the results of that run.
Approach
----------
Whenever a run command is issued to the command processor, we fork an _entire effection tree_ corresponding to the test hierarchy. This allows us to set up a process to track _each_ result, be it step, test, or assertion. If a step fails, we throw an exception which causes every subsequent step and assertion to be disregarded.
Screenshots
------------
=> Report test results through the GraphQL API.

packages/todomvc/app/src/components/Footer.js
Motivation
----------
The vendored TodoMVC app has the following linting warning:
```
./src/components/Footer.js
Line 38:7:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
```
This hasn't been a problem up until now, but suddenly builds started failing for packages in CI because it looks like linting errors are now [magically being treated as errors][1]. This is because github actions were not setting the `CI=true` environment variable, and now they are, …
=> Suppress warning for non-accessible link

packages/agent/app/agent.ts, packages/agent/shared/agent.ts, packages/server/test/helpers.ts
Motivation
----------
As [noted in the pull request that introduced the agent][1], the agent takes responsibility for closing a websocket that was passed into it which is error prone, and likely not composable. Genenally, resources should be setup and torn down by the same locality.
Approach
--------
There were really two options available to us that align ownership of the socket: Either we push the responsibility of destroying of the socket into the outer context, or pull the responsibility for constructing the socket inside the agent context.
If we went with the first option, then it would transfer the burden of maintaining the socket resource to the enclosing scope. In practice, that means needing to have an extra `try/catch/finally` block around the code spanning the lifecycle of the …
=> Symmetric setup and teardown of Agent WebSocket

.github/workflows/release.yml, packages/todomvc/package.json
From [@thefrontside/actions PR #56](https://github.com/thefrontside/actions/pull/56): Need a way to push tags for individual packages within a monorepo (like bigtest) when a pull request gets merged to the master branch.
- What I didn't mention in the pull request I linked above is if someone forgets to bump the version in package.json of the package they worked on, the action will skip the publishing process and still allow the rest of the workflow to continue.
- You can see that [here](https://github.com/thefrontside/bigtest/runs/593032699?check_suite_focus=true).
- This means we never have to worry about accidentally pushing the same tag twice (which would result in an error) unless someone manually pushes tags onto the repository.
- …
=> Update release workflow to push git tags for individual packages

packages/server/bin/subscribe.ts
Motivation
-----------
In order to make working with client subscriptions more friendly to actual clients, [`Client.subscribe` was converted to external iteration][1]. However, the `bin/subscribe.ts` utility was not updated to the new API, which is now [breaking newer builds][2]
Approach
----------
Update the `bin/subscribe` utility to use the new api.
> Note: we did not catch this before because subscribe.ts was not in the tsconfig, and so we were only catching it at runtime when compiling with ts-node. It's debatable whether this should be in the distribution (probably not) but at least we're getting a failure when something breaks about it.
[1]: https://github.com/thefrontside/bigtest/pull/230
[2]: https://github.com/thefrontside/bigtest/pull/236/checks?check_run_id=595782649#step:5:90
=> Convert `yarn subscribe` utility to use new client API

packages/server/.eslintignore, packages/server/package.json, packages/server/src/command-server.ts, packages/server/src/schema.ts, packages/server/src/schema/.gitignore, packages/server/src/schema/context.ts, packages/server/test/command-server.test.ts, yarn.lock
Motivation
----------
We're starting to outgrow our current GraphQL setup which is using a string based schema paired with a rootValue which means that we have perform workarounds when the shape of the atom doesn't correspond to the shape of the GraphQL API. Specifically in the work we're doing to [run multiple test runs on an agent][1]. We need a way to make the resolvers for individual fields pluggable.
Approach
--------
This migrates our GraphQL services to [Nexus][2]. Not only does it have a way of specifying modular resolvers, it lets you do it along side the schema definition, and has the added bonus of typechecking resolvers, contexts, etc...
There is a new yarn script to generate the schema called `yarn generate:schema`. Also, the schema generation is now part of the `prepack` …
=> Use Nexus to both define and implement Graphql Schema

README.md, package.json, packages/server/package.json, packages/website/package.json, packages/website/src/components/Header.tsx, packages/website/src/components/ReachOut.tsx
We have a new Discord channel for BigTest within the Frontside server and needed to update the Bigtest website and readme of this monorepo.
- Update README
- Discord link up top
- Setup instructions updated
- Update package.json of monorepo (author and repository properties to Frontside engineering and frontside/bigtest respectively)
- Update package.json of `packages/server` and `packages/website`
- Update href property of discord links in the website 
- See readme preview [here](https://github.com/thefrontside/bigtest/blob/mk/update-info/README.md)
- Test the new discord links in the website preview [here](https://deploy-preview-242--bigtest.netlify.app/)
=> Add/update Discord links and update package.json

packages/effection/src/mailbox.ts, packages/server/src/orchestrator.ts
In the command processor, we subscribe to the same mailbox many, many times. The underlying EventEmitter complains if there are more than 10 listeners, since it suspects a memory leak. However, in our case, this is expected behaviour, so we should just increase this limit.
=> Mute warning about event listener leak

packages/server/package.json, packages/server/src/schema.ts
> closes #244 
Motivation
-----------
By default, nexus _always_ tries to generate schema artifacts like the `.graphql` schemafile and the typings. However, [this fails in production][1] because it tries to load typescript modules which have long since been compiled into javascript and are not shipped with the distribution.
Approach
----------
Nexus provides a flag to prevent schema generation presumably for cases precisely such as this one. We use this flag here to stop generation unless the `BIGTEST_GENERATE_SCHEMA` environment variable is explicitly set which is done only from the `yarn generate:schema` step.
While this feels a bit awkward and hackish, it's the only workaround that I've been able to find.
[1]: https://github.com/thefrontside/bigtest/issues/244
=> Only generate schema artifacts explicitly

packages/agent/shared/protocol.ts, packages/server/src/command-processor.ts, packages/server/src/command-server.ts, packages/server/src/connection-server.ts, packages/server/src/orchestrator/state.ts, packages/server/src/schema.ts, packages/server/test/command-processor.test.ts, packages/server/test/run-tests.test.ts
Currently when we generate the state for a particular test run, we assume that the test run only has one agent, we did this to simplify things initially, but eventually we want to allow a single test run to run against multiple agents. This PR allows us to track results per agent.
=> Test results should be per-agent

.github/workflows/preview.yml, .github/workflows/release.yml, packages/convergence/package.json, packages/interactor/package.json
To update the release workflow with the latest `synchronize-with-npm` action from [this](https://github.com/thefrontside/actions/pull/58) pull request which introduces the functionality to deprecate packages.
- Added `convergence` and `interactor` directories inside `packages/` with the `"deprecate": true` flag in its respective `package.json`.
- Added `packages/convergence` and `packages/interactor` to the ignore arg for both `preview` and `release` workflows (because we don't need to publish them).
- Updated `synchronize-with-npm` to `v1.6`.
After we merge this pull request, we'll let it deprecate the two packages we already removed from the monorepo. Afterwards I'll create a new pull request to remove those packages once again.
=> Update sync action to v1.6 and reintroduce interactor & convergence to deprecate

.github/workflows/preview.yml, .github/workflows/release.yml, packages/convergence/package.json, packages/interactor/package.json
Part 2 of [this](https://github.com/thefrontside/bigtest/pull/249) pull request and you can see the success of the new action [here](https://github.com/thefrontside/bigtest/runs/613006915).
Both [@bigtest/interactor](https://www.npmjs.com/package/@bigtest/interactor) and [@bigtest/convergence](https://www.npmjs.com/package/@bigtest/convergence) has been deprecated on npmjs.
- Removed `./packages/convergence/package.json` and `./packages/interactor/package.json`.
- Removed `interactor` and `convergence` from the ignore argument of both `release` and `preview` workflows.
=> Remove interactor & convergence and update workflow

package.json, packages/agent/package.json, packages/atom/package.json, packages/cli/package.json, packages/effection-express/package.json, packages/effection/package.json, packages/parcel/package.json, packages/project/package.json, packages/server/package.json, packages/todomvc/package.json, yarn.lock
Motivation
----------
One of the challenges of working with effection inside the bigtest repo has been trying to use a linked version or a preview version and not have things go terribly awry. This is because each package has it listed as a runtime dependency. However, most packages don't actually care that there be a particular version of effection installed, merely that _somme_ version is available. [I _think_ that this is why you want to have peer dependencies.][1]
Throughout our tree, we want to make sure that everyone is handed the same copy of effection (in this case 0.6.2) and the only way to guarantee that is via a peer dependency.
Approach
----------
By using peer dependency everywhere there is a reference to effection, every library will get the same version of effection that is …
=> Upgrade effection, improve linkability

packages/todomvc/package.json, packages/website/package.json, yarn.lock
To address [issue #253](https://github.com/thefrontside/bigtest/issues/253).
```
warning "workspace-aggregator-6a21b4de-1908-4f50-bf13-9fd6a03d9a74 > bigtestjs.io > styled-components@5.0.1" has unmet peer dependency "react-is@>= 16.8.0".
```
`syled-components@^5.0.0` requires `react-is` to be installed. [from their website](https://styled-components.com/docs/faqs)
```
warning "workspace-aggregator-6a21b4de-1908-4f50-bf13-9fd6a03d9a74 > @bigtest/todomvc > react-scripts > eslint-config-react-app@5.2.0" has incorrect peer dependency "eslint-plugin-flowtype@3.x".
```
Incorrect peer dependency bug addressed in react-scripts release [v3.4.1](https://github.com/facebook/create-react-app/releases)
=> Update dependencies to remove warning messages

netlify.toml, packages/website/package.json
To resolve #259: `yarn workspaces run prepack` was building the website unnecessarily and using up resources.
Gatsby workflow does not rely on any `prepack` script and the current `prepack` script is set to `gatsby build`.
- ~~Removed the `command` field in `netlify.toml` so it will just default to `gatsby build`.~~
- Changed the `command` in `netlify.toml` to `gatsby build`.
- Modified the `prepack` script to `echo Skipping prepack for packages/website...`.
- We still need to provide it a `prepack` script or `yarn workspaces` will return an error.
=> Modify prepack script for website

packages/server/src/command-processor.ts, packages/server/test/run-tests.test.ts
If a test has steps, assertions or even children that fail, the test itself should also be marked as failed. This way, we report the status up the tree and are able to report an aggregate status for the entire suite.
It is worth noting that in a user interface, we are most likely interested in mainly showing the status of the *assertions*, not the tests, so while at first glance this might generate a lot of "failure-noise", in practice it probably won't even be visible to the user in most cases, but it will make it much easier to report on the aggregate result of test runs.
=> Percolate failures upwards

packages/agent/package.json, packages/cli/package.json, packages/parcel/package.json, packages/project/package.json, packages/server/package.json, packages/todomvc/package.json
We want to release a public version of bigtest that will actually link-up and run properly in the wild. This means a couple of things:
1. all of the package dependencies need to be there for the package to work IRL.
2. The tarball needs to properly contain the files that will be distributed.
Ran the [knit][1] linter against this repo and it found that in many cases the `files` property of package.json was too conservative and did not select resources into the tarball that were in subdirectories. Also, there were flat-out a lot of dependencies that just weren't specified because they were being implicitly found inside a mono-repo. To be quite honest, I wish `yarn` did not do that.
[1]: https://github.com/knitjs/knit
=> Fix inter-package dependencies

packages/agent/test/agent.test.ts, packages/cli/test/cli.test.ts
It seems to be randomly failing due to github sometimes taking a reaaaaaally long time to start chrome.
=> Increase timeout for agent

packages/agent/test/fixtures/manifest.src.js, packages/suite/package.json, yarn.lock
In preparation for threading the test context, we need to extend the set of test fixtures for the agent, but using the wire format is tedious.
This updates it to use the `test` macro so that we can easily add new steps and assertions
=> Convert the agent test suite to use `test` macro

packages/cli/bigtest.json, packages/cli/src/cli.ts, packages/cli/src/config.ts
Motivation
-----------
Adding commands and sharing code is difficult with the current CLI because it's driven through callbacks via yargs. That means we have to explicitly enter an effection context any time that we want to use an operation. What we'd like is to always be in effection from the get-go.
Approach
----------
This makes the yargs parsing, which is synchronous, a simple function that returns a data structure which can then be used to run the CLI. 
One thing is that there is a chicken and the egg problem with loading the config because we don't know what the config file is until we parse the options and we don't know the all the options until we parse the config. This temporarily punts on this by removing the `config-file` option. What we get in return is better validation of …
=> Turn CLI inside out

packages/interactor/package.json
The latest version of `@bigtest/interactor` that is already published is 0.9.3, but we currently have 0.4.1 in the package.json, which collides with an old version. This is preventing us from publishing this new version.
Change the version to 0.10.0.
=> Fix interactor version to so it doesn't collide with existing versions

packages/cli/src/cli.ts, packages/server/bin/live-query.ts, packages/server/package.json, packages/server/src/client.ts, packages/server/test/command-server.test.ts, packages/server/test/run-tests.test.ts
We will want to use the subscribe/subscription terminology for actual GraphQL subscriptions.
Extracted from #299
=> Rename subscribe -> liveQuery for live queries

.changeset/upgrade-mailbox-to-subscribable.md, packages/effection/package.json, packages/effection/src/mailbox.ts, yarn.lock
Motivation
-----------
With the switch to using subscriptions, `on()` method, the API broke to return an `IteratorResult` instead of just a value for each result of a subscription.
Approach
----------
This updates the `Mailbox` to act as before, except using the underlying Subcription primitive. Since `Mailbox` will most probably be deprecated, this is only a minimal refactor to keep the old API.
=> migrate mailbox to new subscription mechanism

.changeset/subscribable-atom.md, packages/atom/package.json, packages/atom/src/atom.ts, packages/server/src/command-server.ts, yarn.lock
Motivation
-----------
It's easier to implement the `once` and `each` method using subscriptions.
Approach
----------
This just makes `Atom` subscribable, and then refactors current Atom operations to consume itself as a subscription.
Follow-on Work
--------------
- The `each` method is no longer even needed since it is really just a
wrapper around `forEach`. It should be deprecated and removed.
=> Make atom subcribable

.changeset/upgrade-agent-events.md, packages/agent/package.json, packages/atom/src/atom.ts, packages/cli/package.json, packages/cli/test/helpers/stream.ts, packages/effection-express/package.json, packages/effection-express/src/index.ts, packages/parcel/package.json, packages/server/package.json, packages/server/src/client.ts, yarn.lock
Motivation
-----------
There was a breaking change between 0.6.4 and 0.7.1 in @effection/events with the `on()` method which meant that we could no longer install these packages outside the monorepo.
Approach
----------
This upgrades all packages to use the same compatible version of @ffection/events and paves the way for a release of packages that's deployable.
=> upgrade @effection/events

.changeset/fix-project-deps.md, packages/project/package.json
`@bigtest/project` used to have a peer dependency on `@bigtest/webdriver` in order to import some interfaces. We maybe shouldn't have used peer dependency in the first place, but now that the interfaces have been extracted into `@bigtest/driver` there is no dependency at all on webdriver, so let's make it a hard dependency on just the abstract package.
=> Fix @bigtest/project deps

.changeset/fix-server-deps.md, packages/server/package.json
@bigtest/server only uses the `ProjectOptions` interface from `@bigtest/project` and so it doesn't even have any runtime consequences.
This moves the dependency to be a hard dependency (since server does
re-export the ProjectOptions interface)
=> make @bigtest/project a dependency (not peer) of server

.changeset/upgrade-effection.md, package.json, packages/agent/package.json, packages/atom/package.json, packages/cli/package.json, packages/driver/package.json, packages/effection-express/package.json, packages/effection/package.json, packages/parcel/package.json, packages/project/package.json, packages/server/package.json, packages/todomvc/package.json, packages/webdriver/package.json, yarn.lock
Motivation
-----------
We recently changed effection to use a [unique symbol][1] which should make the need to have it as a peer dependency everywhere obsolete. 
Approach
----------
This upgrade effection to the "universal symbol" version and then upgrades all bigtest packages to consume that version as a normal dependency.
=> upgrade effection

.changeset/agentevent-type.md, packages/agent/shared/protocol.ts
We need an interface pertinent to the test run, without meta data.
Split `AgentEvent` into two types, `AgentEvent` and `TestEvent`, where `TestEvent` contains the data relevant to the test run.
=> Split `AgentEvent` type into a union of two types

.changeset/privatize-atom-properties.md, packages/atom/src/atom.ts, packages/atom/test/atom.test.ts, packages/atom/test/helpers.ts, packages/atom/test/project.test.ts
There were no tests for this class.
- Add unit tests
- Make some properties on `Atom` private since they shouldn't be public
=> Add unit tests for `Atom` class

.changeset/atom-set-max-listeners.md, .changeset/atom-subscribable-slice.md, .changeset/graphql-subscriptions.md, packages/agent/shared/protocol.ts, packages/atom/src/atom.ts, packages/atom/src/slice.ts, packages/server/src/client.ts, packages/server/src/command-server.ts, packages/server/src/orchestrator/atom.ts, packages/server/src/orchestrator/state.ts, packages/server/src/protocol.ts, packages/server/src/result-aggregator/assertion.ts, packages/server/src/result-aggregator/step.ts, packages/server/src/result-stream.ts, packages/server/src/schema.ts, packages/server/src/schema/context.ts, packages/server/src/schema/test-event.ts, packages/server/test/result-stream.test.ts, packages/server/test/run-tests.test.ts, packages/server/test/subscription.test.ts, packages/suite/src/interfaces.ts
Converts the stream of states we receive in the atom into a stream of events instead. This event can easily be printed by some CLI tool.
=> GraphQL subscriptions for test events

.github/workflows/preview.yml, .github/workflows/release.yml
[Copied](https://github.com/thefrontside/effection/pull/159) from a similar pull request on `@frontside/effection`:
Whenever we want to publish a release we need to manually checkout, run `yarn changeset version`, git add and push, and then create the pull request on Github. Not only do we need to run the command and create the pull request manually, we also need to update the release branch as more pull requests get merged to the main branch. Using the changeset action will mitigate all those inconveniences.
- Added changeset action to release workflow. When a pull request gets merged it will see if changeset files exist on the repository and if it does it'll create a pull request (or push to a pre-existing release pull request).
- The release action will run regardless of whether or not …
=> Add changeset action to release workflow and conditional to preview

.github/workflows/release.yml
To fix #351.
Forgot to add `run: yarn` prior to the changeset action in the release workflow. 
Adding this command should result in a new pull request created by the changeset action using the changeset files that are currently on the master branch.
=> Run yarn before changeset action

.github/workflows/preview.yml
The pull request generated by the changeset action checkouts a branch with the format `changeset-release/${primary_branch}` so at the moment it will create `changeset-release/master`.
We will need to update the filter again once we change our primary branch to another name.
=> Fix typo so previews aren't published on release PRs

.github/workflows/release.yml
Pull requests created with the default github actions bot do not trigger checks and workflows (in addition to being not branded).
This uses an access token of @frontsidejack to allow running workflows on the PRS that are created as part of the changeset release
=> use @frontsidejack to create changset release pull requests

.github/workflows/changeset.yml, .github/workflows/release.yml
Running both the changeset action and release action in the same workflow was problematic because of the way changeset action checks out to the base branch only to force push to the changeset branch. 
Related to #351, #352, #354, and #355.
There were a few potential workarounds to this issue but we believe letting changeset run in a separate workflow is most appropriate.
- Will wait to see that these workflows work properly before I implement it on effection.
=> Run changeset action in separate workflow

.changeset/bigtest-performance.md, package.json, packages/atom/package.json, packages/atom/test/helpers.ts, packages/cli/package.json, packages/cli/src/run-test.ts, packages/interactor/package.json, packages/interactor/src/converge.ts, packages/performance/.gitignore, packages/performance/CHANGELOG.md, packages/performance/README.md, packages/performance/browser-ponyfill.js, packages/performance/index.d.ts, packages/performance/node-ponyfill.js, packages/performance/package.json, packages/performance/test/ponyfill.test.js, packages/performance/tsconfig.json
the `perf_hooks` package is not available when bundling for the web which was causing bigtest interactors to fail.
This creates a cross-platform ponyfill that can be used to use performance from both. It's written in plain javascript since having a compilation steps seems kinda pointless.
=> add @bigtest/performance

.changeset/distribute-suite-sources.md, packages/suite/package.json
See https://github.com/thefrontside/bigtest/pull/362 for context
This avoids these warnings:
```
⚠️  Could not load source file "../src/index.ts" in source map of "../../../../node_modules/@bigtest/suite/dist/index.js".
⚠️  Could not load source file "../src/dsl.ts" in source map of "../../../../node_modules/@bigtest/suite/dist/dsl.js".
⚠️  Could not load source file "../src/index.ts" in source map of "../../../../node_modules/@bigtest/suite/dist/index.js".
⚠️  Could not load source file "../src/dsl.ts" in source map of "../../../../node_modules/@bigtest/suite/dist/dsl.js".
```
=> distribute sources with npm package

.changeset/config.json, .github/workflows/changeset.yml, .github/workflows/lint.yml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/test.yml
Closes #349 
`master` can be a violent word and make people not feel welcome as an employee or contributor.
Rather than simply changing the name of the default branch, we took a step back and looked at what could be a better branching strategy in general. We've landed on having major release branches (such as `v0`, `v1`, etc.) and setting the default to the latest major release branch. When we begin working on a new major release we:
1. Make a new branch for that version
1. Set the default branch to that version
Note: we will need to change the changeset `config.json` `baseBranch` option manually for each new major release branch.
=> Move to `v*` branches instead of `master`

.changeset/interactor-specification-type.md, packages/interactor/src/create-interactor.ts, packages/interactor/src/interactor.ts, packages/interactor/src/specification.ts
Currently an interactor is typed `Interactor<E extends Element>`, this changes the type to `Interactor<E extends Element, S extends InteractorSpecification<E>>` that is the type of an interactor class and its instance includes a reference to the type of the specification that generated it.
The reason that this is useful is because it allows methods on the interactor to refer to the specification. As part of #359, I would like to add the ability to check for a given filter via `has({ filter: whatever })`, but this requires knowledge of the type of the filter specification to make it type-safe.
Why didn't we do this in the first place then? It does have some downsides. The type of the specification is not easily namable, so when an interactor needs to be referenced somewhere where its type …
=> Interactor is generic over its specification

.changeset/interactor-filters.md, packages/interactor/src/create-interactor.ts, packages/interactor/src/errors.ts, packages/interactor/src/filter.ts, packages/interactor/src/interactor.ts, packages/interactor/src/locator.ts, packages/interactor/src/specification.ts, packages/interactor/test/create-interactor.test.ts, packages/interactor/types/filters.ts
Filters allow the selection of elements to be narrowed. A default value can also be provided. See #310 
I intentionally left this functionality rather minimal.
This also adds the ability to check for filters via an assertion on an interactor like this:
``` typescript
await TextField("Email").has({ value: "test@example.com" });
```
IMO this reads a little better than:
``` typescript
await TextField("Email", { value: "test@example.com" }).exists();
```
=> Add filters to interactors
