thefrontside/bigtest

packages/convergence/README.md
[Rendered](https://github.com/thefrontside/bigtest/blob/ww/convergence-docs/packages/convergence/README.md)
=> Add convergence docs

packages/mocha/CHANGELOG.md, packages/mocha/package.json, packages/mocha/rollup.config.js, packages/mocha/tests/it-test.js, packages/mocha/tests/it.always-test.js, yarn.lock
=> Remove unnecessary commonjs plugin

README.md, packages/mocha/README.md
[rendered](https://github.com/thefrontside/bigtest/blob/ww/mocha-readme/packages/mocha/README.md)
=> Add @bigtest/mocha README

packages/mocha/CHANGELOG.md, packages/mocha/package.json
Added a line to the fixes of the changelog regarding the mocha shim that was most recently merged.
=> @bigtest/mocha v0.2.0

packages/mocha/CHANGELOG.md, packages/mocha/package.json, yarn.lock
Also upgraded `@bigtest/convergence` and added the appropriate changelog entries for this and #50
=> @bigtest/mocha v0.2.1

README.md
=> Remove period after question mark in Markdown

packages/interaction/README.md
Addresses #93 
With the recent `@bigtest/interaction` changes, the README was sadly forgotten about. I've updated references to `Interaction` with `Interactor`, `@page` with `@interactor`, and switched the argument order of a few property helpers. I've also made a few other minor tweaks.
Since the docs site is in progress, this README is by no means final. Once that is complete, we can circle back around and make the READMEs more of an introduction to the package.
=> Update @bigtest/interaction README

packages/website/gatsby-config.js, packages/website/package.json, packages/website/src/components/DidYouKnow.tsx, packages/website/src/components/Header.tsx, packages/website/src/components/WhyBigTest.tsx, packages/website/src/pages/index.tsx, yarn.lock
The institutional fonts are served through Typescript because they're not free. Before, users would only see the font if they had it installed, and the site would default to another option.
Jeffrey created a typescript webkit for us with the fonts we need. Now we serve typescript fonts to the user so everybody sees the same font.
=> Website: Adds typekit fonts 

packages/server/bin/start.ts, packages/server/src/connection-server.ts, packages/server/src/manifest-builder.ts, packages/server/src/manifest-generator.ts, packages/server/src/orchestrator/atom.ts, packages/server/src/orchestrator/state.ts, packages/server/src/test.ts, packages/server/test/fixtures/empty.t.js, packages/server/test/manifest-builder.test.ts, packages/server/test/manifest-generator.test.ts, packages/server/test/orchestrator.test.ts
> Note: this is imported from the original pull request at https://github.com/bigtestjs/server/pull/105
Depends on #159
=> Manifest format

packages/server/src/schema.ts, packages/server/test/command-server.test.ts
=> Fix format of manifest in GraphQL

packages/website/src/components/GreetLegacyUsers.tsx, packages/website/src/components/WarningBox.tsx, packages/website/src/pages/docs.tsx, packages/website/src/pages/guides.tsx, packages/website/src/pages/index.tsx
Two mobile style problems: #168 #164 
Rely on `styled-system` to manage widths for responsive styles.
=> Fix mobile styles

packages/server/test/fixtures/raw-tree-format.t.js
Makes it easier to see iteration through the test suite to have more than one test in there.
=> Add an additional test to the fixture

package.json
=> Build effection utils first, before other packages are built

.github/workflows/test.yml, packages/agent/package.json, packages/agent/src/client.ts, packages/agent/src/index.ts, packages/agent/src/server.ts, packages/agent/test/agent.test.ts, yarn.lock
This uses microsoft's playwright tool for browser automation in the agent testsuite.
=> Use playwright to test agent code

packages/website/src/components/DidYouKnow.tsx, packages/website/src/components/Header.tsx, packages/website/src/components/Text.ts, packages/website/src/components/WhyBigTest.tsx, packages/website/src/pages/index.tsx
The previous copy was not specific enough about how BigTest is bringing new and exciting stuff to the testing ecosystem. 
A new copy was produced and edited. This time it includes many more technical details on what makes BigTest different from existing alternatives. 
Decide on a new slogan.
=> Update landing page copy

packages/server/CHANGELOG.md, packages/server/package.json
> depends on #213 
prepare release v0.1.1
=> release v0.1.1

.github/workflows/test.yml
@cowboyd's [suggestion](https://github.com/thefrontside/bigtest/pull/216) to rename the jobs in the recently added test workflow.
=> Rename jobs in test workflow

packages/effection/CHANGELOG.md, packages/effection/package.json, packages/parcel/package.json, packages/server/package.json
=> @bigtest/effection v0.1.1

yarn.lock
Not sure why these were commited
=> Remove unused packages from yarn.lock

packages/agent/package.json, packages/agent/test/agent.test.ts, yarn.lock
Uses our effection native Webdriver, depends on #257
=> Remove playwright

packages/server/src/result-aggregator/parallel.ts, packages/server/src/result-aggregator/test-run.ts, packages/server/src/result-aggregator/test.ts
Instead of manually munging forks, what about using a parallel helper instead?
=> introduce `parallel` operation.

packages/agent/shared/agent.ts, packages/server/src/command-processor.ts, packages/server/src/command-server.ts, packages/server/src/orchestrator.ts, packages/server/src/result-aggregator/aggregator.ts, packages/server/src/result-aggregator/assertion.ts, packages/server/src/result-aggregator/parallel.ts, packages/server/src/result-aggregator/step.ts, packages/server/src/result-aggregator/test-run-agent.ts, packages/server/src/result-aggregator/test-run.ts, packages/server/src/result-aggregator/test.ts, packages/server/src/schema/context.ts, packages/server/test/command-processor.test.ts, packages/server/test/run-tests.test.ts
extends  #265 
Refactor command processor by extracting a whole bunch of code.
=> Command processor refactor

packages/agent/package.json, packages/atom/package.json, packages/cli/package.json, packages/effection-express/package.json, packages/effection/package.json, packages/logging/package.json, packages/parcel/package.json, packages/project/package.json, packages/server/package.json, packages/suite/package.json, packages/todomvc/package.json, packages/webdriver/package.json, yarn.lock
=> Prepare release 0.4.0 for all packages

packages/cli/test/cli.test.ts, packages/suite/package.json, packages/suite/src/dsl.ts, packages/suite/src/index.ts, packages/suite/src/interfaces.ts, packages/suite/test/dsl.test.ts, packages/suite/test/fixtures/example.ts, packages/suite/tsconfig.json, packages/suite/types/dsl.ts, packages/suite/types/index.d.ts, packages/suite/types/tsconfig.json, yarn.lock
This adds a basic DSL for the test suite syntax
=> Add DSL for test suite

packages/agent/package.json, packages/atom/package.json, packages/cli/package.json, packages/effection-express/package.json, packages/effection/package.json, packages/logging/package.json, packages/parcel/package.json, packages/project/package.json, packages/server/package.json, packages/suite/CHANGELOG.md, packages/suite/package.json, packages/todomvc/package.json, packages/webdriver/package.json
=> Prepare 0.4.1

packages/server/src/proxy.ts
Motivation
-----------
It turns out we were cheating a bit and installing our top level event handlers directly on the proxy `http.Server` object, and not actually entering an effection context at all until we'd received the upstream response from the proxy target. This becomes a problem when you are shutting down your process while you have proxy requests in-flight since the upstream target will stop responding, causing an uncaught http exception when the request tries to continue reading bytes from it.
Approach
----------
This converts both of the raw event handlers (web, and websocket) into `@effection/events` subscriptions that shutdown each request if the effection context happens to be destroyed mid-request.
In the case of normal http requests we wait until the response is fully …
=> Always handle proxy events within effection context.

packages/cli/bigtest.json, packages/cli/src/cli.ts, packages/cli/src/config.ts, packages/cli/test/cli.test.ts, packages/project/src/index.ts
This command both starts the server and runs the tests, this is useful in CI mode, but should probably be avoided in development mode most of the time.
=> Add CI command for CLI

packages/interactor/src/define-interactor.ts, packages/interactor/src/errors.ts, packages/interactor/src/options.ts, packages/interactor/test/define-interactor.test.ts
This adds a hook on the interactor library so we can disable actions, it remains to be solved how we hook this up into the runner.
=> Add hook to disable actions

package.json, yarn.lock
This switches the version to the microbundle, build with sources
=> upgrade effection to 0.6.4

packages/driver/package.json
One more got past https://github.com/thefrontside/bigtest/pull/324
=> Switch to frontside.com domain

.changeset/cli-dry.md, packages/cli/src/cli.ts, packages/cli/src/config.ts, packages/cli/src/run-test.ts, packages/cli/src/start-server.ts
There is currently a whole bunch of duplication in the CLI, since we want to add subscriptions and have one nice place to add this, we should start off by simply drying up the code a bit so it is easier to modify.
=> DRY up CLI

packages/cli/src/cli.ts, packages/cli/src/format-helpers.ts, packages/cli/src/formatters/lines.ts, packages/cli/src/query.ts, packages/cli/src/run-test.ts, packages/cli/test/cli.test.ts
Depends on #344 
This allows us to finally actually output some decent test results! 🥳
=> Add streaming output of test results

.changeset/cli-streaming.md
=> Add changeset for streaming formatter in CLI package
